# Generated by Django 3.1.5 on 2021-01-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NotKnown', max_length=150)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.TextField(default='', help_text='Click to add description', max_length=500)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
